//VENTANA
#define W_WIDTH 800
#define W_HEIGHT 600

//JUEGO
#define VELOCITY 3
#define N_ESCUDOS 3

//TAMAÑOS
#define TAM_JUG_X W_WIDTH/25
#define TAM_JUG_Y W_HEIGHT/5
#define TAM_SHIELD_X 25
#define TAM_SHIELD_Y 50
#define TAM_BULLET_X 50
#define TAM_BULLET_Y 25

//POSICIONES INICIALES
#define X_INI W_WIDTH/30
#define X_INI_2 W_WIDTH-(W_WIDTH/30)-TAM_JUG_X
#define Y_INI W_HEIGHT/2